### PR TITLE
Added Pricing Card Deck 

### LINKED ISSUE #76: Pricing Card Deck
**Is your feature request related to a problem? Please describe.**
Pricing Card Deck is a three-card component that displays pricing and the available features corresponding to that price for any product. It has Annual and Monthly option also. This can be reused as a template to display any pricing related cards.

**Describe the solution you'd like**
It is built using HTML, CSS, and JS, without any front-end frameworks like Bootstrap, Tailwind CSS, etc.

### PR DESCRIPTION
**Pull request by kiruba-r11**
# Description

Pricing Card Deck is a three-card component that displays pricing and the available features corresponding to that price for any product. It has Annual and Monthly option also. This can be reused as a template to display any pricing-related cards.

Fixes #76 

## Type of change

- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
@kiruba-r11 resolve conflict

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
Resolve Conflict

**Comment by kiruba-r11** [comment]
@Ayush7614 I have resolved the conflict

**Pull request merged**
