### PR TITLE
pet rescue

### PR DESCRIPTION
**Pull request by ritweekraj2802**

### CODE REVIEW

**Review by Ayush7614 — CHANGES_REQUESTED** [review]
Mention your issue no

**Comment by ritweekraj2802** [comment]
Pet rescue - 610
sticky navigation - 611

**Comment by ritweekraj2802** [comment]
pairs game -612

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
remove .vs files

**Comment by Ayush7614** [comment]
Close due to no activity

**Pull request closed without merging**
