### PR TITLE
Sign up Page added

### PR DESCRIPTION
**Pull request by Abhicoder03**
# I have added a sign up using html,css.

Fixes #(241)

### CODE REVIEW

**Comment by Ayush7614** [comment]
Mention your issue no only with #

**Comment by Ayush7614** [comment]
and also mention under which program you can contribute

**Comment by Abhicoder03** [comment]
# 241
Program - Hacktoberfest

**Comment by Abhicoder03** [comment]
@Ayush7614 I'll close this PR and send another one.

**Pull request closed without merging**
