### PR TITLE
Social Media dashboard with theme switcher created. 

### PR DESCRIPTION
**Pull request by Antara25-10**
# Description

I have added the functionalities and the desired themes of the dashboard

### CODE REVIEW

**Comment by Ayush7614** [comment]
mention your issue no and mention your program under which you contribute

**Comment by Antara25-10** [comment]
@Ayush7614 issue no.333 and I want to contribute it under Hacktoberfest 2021

**Comment by Antara25-10** [comment]
@Ayush7614 ??

**Comment by Ayush7614** [comment]
PR Close due to no activity

**Pull request closed without merging**
