### PR TITLE
Fully Responsive Tracker Expense Calculator Added.

### LINKED ISSUE #866: Fully Responsive Tracker-Expense Calculator (HTML, CSS, JavaScript)
**Is your feature request related to a problem? Please describe.**
- Mostly, people are not able to take care of their expenses and control their over-budgets.
- I have designed an easy-to-use expense calculator which will help user to calculate their monthly expenses.
- Users can maintain a record of their monthly expenses by saving them as cards and can control their budgets for the next time.

**Describe the solution you'd like**
- I would like to add my Tracker-Expense Calculator project to your website. I am a GSSOC'22 participant, kindly assign this issue to me. Thank you.

**Describe alternatives you've considered**
Same as above.

**Additional context**

image

image

### PR DESCRIPTION
**Pull request by KiranAminPanjwani**
# Description

- I have designed an easy-to-use expense calculator which will help user to calculate their monthly expenses.
- Users can maintain a record of their monthly expenses by saving them as cards.

image

image

image

Fixes #866 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
@Ayush7614 Kindly review and merge it. Thank you.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by KiranAminPanjwani** [comment]
@gurjeetsinghvirdee Thank you so much for merging it!✨

**Comment by KiranAminPanjwani** [comment]
> @gurjeetsinghvirdee Thank you so much for merging it!✨

Kindly update the leaderboard 💥.

**Comment by gurjeetsinghvirdee** [comment]
> > @gurjeetsinghvirdee Thank you so much for merging it!✨
> 
> Kindly update the leaderboard 💥.

Leaderboard update itself with the help of Github action

**Pull request merged**
