### PR TITLE
Discord clone

### PR DESCRIPTION
**Pull request by Rajdip019**
# Description

Added Discord Clone

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [  ] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

Screenshot 2022-03-01 231837

### CODE REVIEW

**Comment by Ayush7614** [comment]
image

**Review by Ayush7614 — CHANGES_REQUESTED** [review]
@Rajdip019 what is this please remove your previous commit and added code properly there is nothing in this PR and if you make second PR then make different branch and follow all the git bash commands for making PR

**Comment by Ayush7614** [comment]
And also linked your issue no with the PR

**Comment by gurjeetsinghvirdee** [comment]
closing this issue bcoz of no response

**Pull request closed without merging**
