### PR TITLE
Registration form

### PR DESCRIPTION
**Pull request by sejal1126**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(234)

Replace `234` with the issue number which is fixed in this PR

## Type of change

Created Registration using HTML AND CSS.
This form consist of
1 First Name
2 Last Name
3 Email ID
4 Phone number
5 Branch 
6 Year
7 Gender
For every title created seperate classes.

"I havn't put background image because of copyright issue but have implemented this feature".

### CODE REVIEW

**Comment by sejal1126** [comment]
Please let me know anything required more in this.

**Comment by sejal1126** [comment]
Please let me know anything required more in this.

**Comment by Ayush7614** [comment]
Mention Your Issue no with #

**Comment by sejal1126** [comment]
I fixes issue #237

**Pull request merged**
