### PR TITLE
✨ add BMI calculator

### LINKED ISSUE #5: BMI Calculator in JS

### PR DESCRIPTION
**Pull request by shvam0000**
# Description

Add BMI Calculator

Fixes #5 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
Mention Screenshot of output in README

**Comment by shvam0000** [comment]
> Mention Screenshot of output in README

In the Main repo readme or specific project's readme?

**Comment by shvam0000** [comment]
I have updated the app and built it using React and Tailwindcss now. I've added the screenshot in the main 'Bundli-Frontend' Readme and have created a Readme for the project itself.

**Comment by Ayush7614** [comment]
@shvam0000 Resolve Conflict

**Comment by shvam0000** [comment]
> @shvam0000 Resolve Conflict

Done, please check once

**Pull request merged**
