### PR TITLE
Added Disney Plus Implementation

### LINKED ISSUE #789: Added Disney Plus
# Aim
- Want to add implementation of frontend of Disney Plus

Kindly assign this issue to me @Ayush7614

### PR DESCRIPTION
**Pull request by hariketsheth**
# Description
Fixes #789 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

## Reference Used 
https://www.youtube.com/watch?v=ZeY9RicS2js&t=1s

## Screenshots
image

image

### CODE REVIEW

**Comment by hariketsheth** [comment]
@Ayush7614 Please review

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee Please review this. No Response from quite some time

**Comment by gurjeetsinghvirdee** [comment]
Copied from here https://www.youtube.com/watch?v=ZeY9RicS2js&t=1s

**Comment by hariketsheth** [comment]
> Copied from here https://www.youtube.com/watch?v=ZeY9RicS2js&t=1s

But if a person have implemented it, how does that count for Plagiarism.
In that case, everyone should be booked for plagiarism for copying the tags and syntax from official documentation of that programming language. 

I seriously didn't find this to be a justified action on this particular PR.

**Comment by hariketsheth** [comment]
Everyone sees tutorials, takes some help, and implements the things. In today's scenario, clone of everything is either available on Youtube as a video or in form of code in some Github repository. Then how does is it fair to count this PR for Plagiarism ?

**Comment by gurjeetsinghvirdee** [comment]
then mention that you take reference how could we know that you are taking reference

**Pull request merged**
