### PR TITLE
Added youtube video player clone

### LINKED ISSUE #705: Add YouTube video player clone
**Is your feature request related to a problem? Please describe.**
Create YouTube video player with play and pause control along with full screen mode, volume slider,  close captions etc

**Describe the solution you'd like**
I will use HTML, CSS, Javascript for this project

**Additional context**

This is meant to be a clone of the YouTube video player and not the website with as many of  the advanced video controls present in it as possible

I am a GSSOC 22 contributor. Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Adhetya**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Added a fully functional, responsive youtube video player clone:
## Features:
- Play/pause functionality
- Volume slider 
- Theatre mode
- Full Screen mode
- Keyboard functionality(eg: m for mute and other keyboard shortcuts have been added as well)
-Note: Deleted all .DS_Store files

Fixes #705 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

## Video demo:

https://user-images.githubusercontent.com/20537150/170824928-7fa34ee6-444c-45ed-a85f-8bad9fe4f4bc.mp4

### CODE REVIEW

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
remove all other project folders

**Comment by Adhetya** [comment]
@gurjeetsinghvirdee, the project folders where .DS_Store was removed?

> remove all other project folders

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee, the project folders where .DS_Store was removed?
> 
> > remove all other project folders

if I merge this then the other folders will be deleted from the original branch

**Comment by Adhetya** [comment]
@gurjeetsinghvirdee, only .DS_Store was deleted in the other projects. Other files are still there

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee, only .DS_Store was deleted in the other projects. Other files are still there

oh okay

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
