### PR TITLE
Added transform toggle animation 

### LINKED ISSUE #98: Transform toggle animation
# Aim

- to add transform toggle animation

# Details

-  It will have 4 cards.
- When you click on one card the other card becomes light and small in size and many more effects
- The card which is clicked also has some effects.

### PR DESCRIPTION
**Pull request by siddhi-244**
# Description

ADDED TRANSFORM TOGGLE ANIMATION IN CSS.

Fixes #98 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
Resolve Conflict

**Comment by siddhi-244** [comment]
Done sir !

**Comment by Ayush7614** [comment]
Not done siddhi

**Comment by Ayush7614** [comment]
Okk dont worry i will resolve

**Comment by siddhi-244** [comment]
Thank you sir !

**Pull request merged**
