### PR TITLE
wall breaker

### PR DESCRIPTION
**Pull request by nikhv**
# Description
Added wall breaker game using HTML, CSS and JS
you can move the paddle to left and right using the key
destroying the wall's will earn you a point and it will increase the score

Fixes #(198)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
@nikhv image

**Comment by Ayush7614** [comment]
@nikhv plss mention issue no only with #

**Comment by Ayush7614** [comment]
and resolve conflict

**Comment by nikhv** [comment]
issue #198

**Pull request merged**
