### PR TITLE
Neumorphic Music Player (#8)

### LINKED ISSUE #8: Music Player in JS

### PR DESCRIPTION
**Pull request by varunwho**
# Description

Music player using Vanilla JS with a neumorphic design

Fixes #8 

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

musicPlayer

### CODE REVIEW

**Comment by Ayush7614** [comment]
@varunwho Resolve Conflict

**Comment by varunwho** [comment]
> @varunwho Resolve Conflict

Done!

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
Resolve Conflict

**Comment by varunwho** [comment]
Done!

Screenshot 2021-06-29 041112

**Pull request merged**
