### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by PadminiRai**
# Description

Created a weather app in HTML,CSS,JS and used API for weather information.

Fixes https://github.com/Ayush7614/Bundli-Frontend/issues/40

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update
- [X] Documentation Update

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
@PadminiRai Resolve Conflict

**Comment by PadminiRai** [comment]
> @PadminiRai Resolve Conflict

Resolved.

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
Not Resolved

**Comment by PadminiRai** [comment]
> Not Resolved

@Ayush7614 that keeps on happening because PRs get merged and README is updated accordingly , whenever I resolve the conflict , other PRs get merged and README is updated again.

**Pull request merged**
